name: Verify Signed-off-by

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify_signed_off_commits:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Verify Signed-off-by trailer
        run: |
          set -e
          BASE_SHA=$(git merge-base origin/${{ github.event.repository.default_branch }} HEAD)
          HEAD_SHA=HEAD
          echo "Checking commits from $BASE_SHA to $HEAD_SHA"
          COMMITS=$(git rev-list --no-merges "$BASE_SHA..$HEAD_SHA")
          for COMMIT in $COMMITS; do
            echo "Checking commit $COMMIT"
            if ! git show -s --format=%B "$COMMIT" | grep -qi "^Signed-off-by:"; then
              echo "ERROR: commit $COMMIT is missing Signed-off-by trailer."
              exit 1
            fi
          done
          echo "All commits contain Signed-off-by trailer."
